services:
  goback:
    build: .
    depends_on: 
      - db
    ports:
      - "8000:8000"
    environment:
      GOBACK_MYSQL_URI: "mysql+pymysql://goback_usr:goback_usr1234@db:3306/goback"
      GOBACK_KEY: ${GOBACK_KEY}

      GOBACK_ENDPOINT_URL: ${GOBACK_ENDPOINT_URL}
      GOBACK_PROJECT_ID: ${GOBACK_PROJECT_ID}
      GOBACK_STORAGE_BUCKET_ID: ${GOBACK_STORAGE_BUCKET_ID}
  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: goback
      MYSQL_USER: goback_usr
      MYSQL_PASSWORD: goback_usr1234
    volumes:
      - mysql_data:/var/lib/mysql



volumes:
  mysql_data:

